### ISSUE TITLE
missing function "init_mart_human_grch37"

### ISSUE THREAD

**Issue by aarthi-mohan** [naumenko-sa/bioscripts#2]
Hi there,

I am trying to use the 'genes.R' script and bringing to your attention that the file might be missing the  'init_mart_human_grch37()' function definition. 

`Rscript ~/bioscripts/gene_panels/genes.R phenotips_hpo2gene_coordinates 1111.tsv`
```
Error in init_mart_human_grch37() :
  could not find function "init_mart_human_grch37"
Calls: fcn
In addition: Warning message:
replacing previous import 'BiocGenerics::dims' by 'Biobase::dims' when loading 'AnnotationDbi'
Execution halted
```

Thanks,
Aarthi

**Comment by naumenko-sa** [comment]
HI @aarthi-mohan !

Thanks for reporting, you are right.

I've fixed it here: https://github.com/naumenko-sa/bioscripts/blob/master/gene_panels/genes.R#L334

Sergey
